# ============ METADATA ============
name: gh-oss-stats
description: Generate Badge To Showcase Your Open Source Contributions
author: mabd-dev

branding:
  icon: 'award'
  color: 'green'


# ============= INPUTS ==============
inputs:
  username: 
    description: Github username
    required: true
    default: ${{ github.repository_owner }}

  github-token:
    description: Github Token for API access
    required: true

  include-loc:
    description: Include LOC (Lines Of Code) metrics
    default: 'true'

  min-stars:
    description: Minimum repo stars
    default: 0

  max-prs:
    description: Max PRs to fetch
    default: 500

  exclude-orgs:
    description: Comma-separated list of organizations to exclude
    default: ""

  timeout:
    description: Timeout in seconds
    default: '300'

  verbose:
    description: 'Enable verbose logging for debugging'
    default: 'false'

  debug:
    description: Uses fake data when true
    default: 'false'

  # ==== Badge Falgs ====
  badge-style:
    default: 'summary'

  badge-variant:
    default: 'default'

  badge-theme:
    default: 'dark'

  badge-output-path:
    description: Output path for the badge
    default: 'oss-stats.svg'

  badge-sort:
    default: 'prs'

  badge-limit:
    default: 5

  # ==== Action Flags ====
  commit-badge:
    description: 'Automatically commit and push the generated badge'
    default: 'true'

  commit-message:
    description: Commit message when auto-commit badge
    default: 'Update OSS contribution badge'

  version:
    description: Version of mabd-dev/gh-oss-stats to use
    default: latest


# ============ EXECUTION ============
runs:
  using: 'composite'
  steps:
    # TODO: add input validation step
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Install gh-oss-stats
      shell: bash
      run: |
        echo "::group::Installing gh-oss-stats CLI"
        go install github.com/mabd-dev/gh-oss-stats/cmd/gh-oss-stats@latest
        echo "✅ gh-oss-stats installed successfully"
        echo "::endgroup::"

    # TODO: after badge generated, verify it's actually generated 
    - name: Generate badge
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        echo "::group::Generating OSS contribution badge"

        gh-oss-stats \
          --user ${{ inputs.username }} \
          --include-loc=${{ inputs.include-loc }} \
          --min-stars ${{ inputs.min-stars }} \
          --max-prs ${{ inputs.max-prs }} \
          --exclude-orgs ${{ inputs.exclude-orgs }} \
          --verbose=${{ inputs.verbose }} \
          --timeout ${{ inputs.timeout }} \
          --debug=${{ inputs.debug }} \
          --badge \
          --badge-style ${{ inputs.badge-style }} \
          --badge-variant ${{ inputs.badge-variant }} \
          --badge-theme ${{ inputs.badge-theme }} \
          --badge-sort ${{ inputs.badge-sort }} \
          --badge-output ${{ inputs.badge-output-path }} \
          --badge-limit ${{ inputs.badge-limit }}

        echo "✅ Badge generated successfully ($BADGE_SIZE bytes)"
        echo "::endgroup::"

    - name: Commit changes
      if: inputs.commit-badge == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ inputs.commit-message }}
        file_pattern: ${{ inputs.badge-output-path }}
