# ============ METADATA ============
name: gh-oss-stats
description: Generate Badge To Showcase Your Open Source Contributions
author: mabd-dev

branding:
  icon: 'award'
  color: 'green'


# ============= INPUTS ==============
inputs:
  username: 
    description: Github username
    required: true

  github-token:
    description: Github Token for auth Github API requests
    required: true

  include-loc:
    description: Include LOC (Lines Of Code) metrics
    default: 'true'

  min-stars:
    description: Minimum repo stars
    default: 0

  max-prs:
    description: Max PRs to fetch
    default: 500

  exclude-orgs:
    description: Comma-separated list of organizations to exclude
    default: ""

  verbose:
    description: Verbose logging to stderr
    default: 'false'

  timeout:
    description: Timeout in seconds
    default: '300'

  # ==== Badge Falgs ====
  badge-style:
    default: 'summary'

  badge-variant:
    default: 'default'

  badge-theme:
    default: 'dark'

  badge-output:
    description: Output path for the badge
    default: 'oss-stats.svg'

  badge-sort:
    default: 'prs'

  badge-limit:
    default: 5

  # ==== Action Flags ====
  auto-commit:
    description: Automatically commit changes
    default: 'true'

  commit-message:
    description: 'Commit message for auto-commit'
    default: 'Update OSS stats badge'

  version:
    description: Version of mabd-dev/gh-oss-stats to use
    default: latest


# ============ EXECUTION ============
runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Install gh-oss-stats
      shell: bash
      run: go install github.com/mabd-dev/gh-oss-stats/cmd/gh-oss-stats@${{ inputs.version }}

    - name: Generate badge
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        gh-oss-stats \
          --user ${{ inputs.username }} \
          --include-loc=${{ inputs.include-loc }} \
          --min-stars ${{ inputs.min-stars }} \
          --max-prs ${{ inputs.max-prs }} \
          --exclude-orgs ${{ inputs.exclude-orgs }} \
          --verbose=${{ inputs.verbose }} \
          --timeout ${{ inputs.timeout }} \
          --badge \
          --badge-style ${{ inputs.badge-style }} \
          --badge-variant ${{ inputs.badge-variant }} \
          --badge-theme ${{ inputs.badge-theme }} \
          --badge-sort ${{ inputs.badge-sort }} \
          --badge-output ${{ inputs.badge-output }} \
          --badge-limit ${{ inputs.badge-limit }}

    - name: Commit changes
      if: inputs.auto-commit == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ inputs.commit-message }}
        file_pattern: ${{ inputs.badge-output }}
